// js/words-data.js
export const dailyWords = {
    "September 1": [
        { word: "It's dark outside", translation: "темно на улице", image: "images/its_dark_outside.jpg", audio: "audio/its_dark_outside.mp3" },
        { word: "So", translation: "поэтому", image: "images/so.jpg", audio: "audio/so.mp3" },
        { word: "Come to work", translation: "прийти на работу", image: "images/come_to_work.jpg", audio: "audio/come_to_work.mp3" },
        { word: "Go to work by bus", translation: "поехать на работу на автобусе", image: "images/go_to_work_by_bus.jpg", audio: "audio/go_to_work_by_bus.mp3" },
        { word: "Leave my belongings at work", translation: "оставить свои (личные) вещи на работе", image: "images/leave_my_belongings.jpg", audio: "audio/leave_my_belongings.mp3" },
        { word: "Stay consistent with your studies", translation: "быть последовательным в учебе / регулярно заниматься", image: "images/stay_consistent.jpg", audio: "audio/stay_consistent.mp3" },
        { word: "Get dressed", translation: "одеться", image: "images/get_dressed.jpg", audio: "audio/get_dressed.mp3" },
        { word: "Bark", translation: "лаять", image: "images/bark.jpg", audio: "audio/bark.mp3" },
        { word: "Neighbours", translation: "соседи", image: "images/neighbours.jpg", audio: "audio/neighbours.mp3" },
        { word: "Live on the eighth floor", translation: "жить на 8 этаже", image: "images/live_eighth_floor.jpg", audio: "audio/live_eighth_floor.mp3" },
        { word: "Go upstairs", translation: "подняться наверх", image: "images/go_upstairs.jpg", audio: "audio/go_upstairs.mp3" },
        { word: "Live next door", translation: "жить по соседству", image: "images/live_next_door.jpg", audio: "audio/live_next_door.mp3" },
        { word: "Talk loudly", translation: "разговаривать громко", image: "images/talk_loudly.jpg", audio: "audio/talk_loudly.mp3" },
        { word: "Talk quietly", translation: "разговаривать тихо", image: "images/talk_quietly.jpg", audio: "audio/talk_quietly.mp3" },
        { word: "Argue all the time", translation: "ругаться все время", image: "images/argue_all_the_time.jpg", audio: "audio/argue_all_the_time.mp3" },
        { word: "Call somebody", translation: "звонить кому-то", image: "images/call_somebody.jpg", audio: "audio/call_somebody.mp3" },
        { word: "Talk on the phone with someone", translation: "разговаривать с кем-то по телефону", image: "images/talk_on_phone.jpg", audio: "audio/talk_on_phone.mp3" },
        { word: "Maybe / probably", translation: "возможно", image: "images/maybe_probably.jpg", audio: "audio/maybe_probably.mp3" },
        { word: "Talk about something good", translation: "разговаривать о чем-то хорошем", image: "images/talk_something_good.jpg", audio: "audio/talk_something_good.mp3" },
        { word: "Sleep until lunchtime", translation: "спать до обеда", image: "images/sleep_until_lunchtime.jpg", audio: "audio/sleep_until_lunchtime.mp3" },
        { word: "Go straight ahead until you see the store", translation: "идти прямо пока не увидишь магазин", image: "images/go_straight_ahead.jpg", audio: "audio/go_straight_ahead.mp3" },
        { word: "Work until 5.30", translation: "работать до 5.30", image: "images/work_until_530.jpg", audio: "audio/work_until_530.mp3" },
        { word: "Before school", translation: "до школы", image: "images/before_school.jpg", audio: "audio/before_school.mp3" },
        { word: "Before", translation: "перед тем как, до", image: "images/before.jpg", audio: "audio/before.mp3" },
        { word: "After", translation: "после", image: "images/after.jpg", audio: "audio/after.mp3" },
        { word: "Appreciate them", translation: "ценить их", image: "images/appreciate_them.jpg", audio: "audio/appreciate_them.mp3" },
        { word: "Get on really well", translation: "хорошо ладить", image: "images/get_on_well.jpg", audio: "audio/get_on_well.mp3" },
        { word: "Just a movie", translation: "просто фильм", image: "images/just_a_movie.jpg", audio: "audio/just_a_movie.mp3" },
        { word: "Bad for hearing", translation: "плохо для слуха", image: "images/bad_for_hearing.jpg", audio: "audio/bad_for_hearing.mp3" },
        { word: "Bother", translation: "мешать, беспокоить", image: "images/bother.jpg", audio: "audio/bother.mp3" },
        { word: "Definition", translation: "определение (слова)", image: "images/definition.jpg", audio: "audio/definition.mp3" },
        { word: "Skill", translation: "навык", image: "images/skill.jpg", audio: "audio/skill.mp3" },
        { word: "Shy", translation: "стеснительный", image: "images/shy.jpg", audio: "audio/shy.mp3" },
        { word: "In the same area", translation: "в одном и том же районе, территории", image: "images/same_area.jpg", audio: "audio/same_area.mp3" },
        { word: "Get the train to Astana", translation: "сесть на поезд до Астаны", image: "images/train_to_astana.jpg", audio: "audio/train_to_astana.mp3" },
        { word: "It gets dark early", translation: "темнеет рано", image: "images/gets_dark_early.jpg", audio: "audio/gets_dark_early.mp3" },
        { word: "Everywhere", translation: "везде", image: "images/everywhere.jpg", audio: "audio/everywhere.mp3" },
        { word: "Underground / subway", translation: "метро", image: "images/subway.jpg", audio: "audio/subway.mp3" },
        { word: "It Means", translation: "это означает", image: "images/it_means.jpg", audio: "audio/it_means.mp3" },
        { word: "Get a permit", translation: "получить разрешение", image: "images/get_permit.jpg", audio: "audio/get_permit.mp3" },
        { word: "Pass an audition", translation: "пройти прослушивание", image: "images/pass_audition.jpg", audio: "audio/pass_audition.mp3" },
        { word: "Share a room with my sister", translation: "делить комнату с сестрой", image: "images/share_room.jpg", audio: "audio/share_room.mp3" },
        { word: "Flat / apartment", translation: "квартира", image: "images/apartment.jpg", audio: "audio/apartment.mp3" },
        { word: "Write your own songs", translation: "писать свои собственные песни", image: "images/write_songs.jpg", audio: "audio/write_songs.mp3" },
        { word: "It gets cold", translation: "холодает", image: "images/it_gets_cold.jpg", audio: "audio/it_gets_cold.mp3" },
        { word: "Audience", translation: "публика", image: "images/audience.jpg", audio: "audio/audience.mp3" },
        { word: "Pants / trousers", translation: "брюки", image: "images/pants.jpg", audio: "audio/pants.mp3" },
        { word: "Shoes", translation: "обувь", image: "images/shoes.jpg", audio: "audio/shoes.mp3" },
        { word: "Dress", translation: "платье", image: "images/dress.jpg", audio: "audio/dress.mp3" },
        { word: "Dress in black", translation: "одеваться в черное", image: "images/dress_in_black.jpg", audio: "audio/dress_in_black.mp3" },
        { word: "Shorts", translation: "шорты", image: "images/shorts.jpg", audio: "audio/shorts.mp3" },
        { word: "Spill coffee on your shirt", translation: "пролить кофе на рубашку", image: "images/spill_coffee.jpg", audio: "audio/spill_coffee.mp3" },
        { word: "Half past 9 - 9.30", translation: "половина десятого", image: "images/half_past_9.jpg", audio: "audio/half_past_9.mp3" },
        { word: "Get the wrong size", translation: "взять не тот размер", image: "images/wrong_size.jpg", audio: "audio/wrong_size.mp3" },
        { word: "This (is)", translation: "это (ед.ч)", image: "images/this_is.jpg", audio: "audio/this_is.mp3" },
        { word: "That (is)", translation: "то, тот, та", image: "images/that_is.jpg", audio: "audio/that_is.mp3" },
        { word: "These (are)", translation: "это(эти) (мн.ч)", image: "images/these_are.jpg", audio: "audio/these_are.mp3" },
        { word: "Those (are)", translation: "те (мн.ч)", image: "images/those_are.jpg", audio: "audio/those_are.mp3" },
        { word: "Here", translation: "здесь, сюда", image: "images/here.jpg", audio: "audio/here.mp3" },
        { word: "There", translation: "там, туда", image: "images/there.jpg", audio: "audio/there.mp3" },
        { word: "Over there", translation: "вон там, вон туда", image: "images/over_there.jpg", audio: "audio/over_there.mp3" },
        { word: "Eraser", translation: "стерка", image: "images/eraser.jpg", audio: "audio/eraser.mp3" },
        { word: "Parts of the body", translation: "части тела", image: "images/parts_of_body.jpg", audio: "audio/parts_of_body.mp3" },
        { word: "Head", translation: "голова", image: "images/head.jpg", audio: "audio/head.mp3" },
        { word: "Hair", translation: "волосы", image: "images/hair.jpg", audio: "audio/hair.mp3" },
        { word: "Face", translation: "лицо", image: "images/face.jpg", audio: "audio/face.mp3" },
        { word: "Eyes", translation: "глаза", image: "images/eyes.jpg", audio: "audio/eyes.mp3" },
        { word: "Ears", translation: "уши", image: "images/ears.jpg", audio: "audio/ears.mp3" },
        { word: "Nose", translation: "нос", image: "images/nose.jpg", audio: "audio/nose.mp3" },
        { word: "Mouth", translation: "рот", image: "images/mouth.jpg", audio: "audio/mouth.mp3" },
        { word: "Lips", translation: "губы", image: "images/lips.jpg", audio: "audio/lips.mp3" },
        { word: "Neck", translation: "шея", image: "images/neck.jpg", audio: "audio/neck.mp3" },
        { word: "Arms", translation: "руки", image: "images/arms.jpg", audio: "audio/arms.mp3" },
        { word: "Wash your hands", translation: "помыть руки", image: "images/wash_hands.jpg", audio: "audio/wash_hands.mp3" },
        { word: "Fingers", translation: "пальцы", image: "images/fingers.jpg", audio: "audio/fingers.mp3" },
        { word: "Shoulders", translation: "плечи", image: "images/shoulders.jpg", audio: "audio/shoulders.mp3" },
        { word: "Legs", translation: "ноги", image: "images/legs.jpg", audio: "audio/legs.mp3" },
        { word: "Foot", translation: "нога", image: "images/foot.jpg", audio: "audio/foot.mp3" },
        { word: "Feet", translation: "ступни", image: "images/feet.jpg", audio: "audio/feet.mp3" },
        { word: "It's something that", translation: "это что то что", image: "images/its_something_that.jpg", audio: "audio/its_something_that.mp3" },
        { word: "Describe", translation: "описывать", image: "images/describe.jpg", audio: "audio/describe.mp3" },
        { word: "Fall from the sky", translation: "падать с неба", image: "images/fall_from_sky.jpg", audio: "audio/fall_from_sky.mp3" },
        { word: "It's something that people wear on their ears", translation: "это что то что люди одевают на свои уши", image: "images/wear_on_ears.jpg", audio: "audio/wear_on_ears.mp3" },
        { word: "To protect them from cold", translation: "чтобы защитить от холода", image: "images/protect_from_cold.jpg", audio: "audio/protect_from_cold.mp3" },
        { word: "It looks like a human", translation: "это выглядит как человек", image: "images/looks_like_human.jpg", audio: "audio/looks_like_human.mp3" },
        { word: "Cozy", translation: "уютный", image: "images/cozy.jpg", audio: "audio/cozy.mp3" },
        { word: "It's not true", translation: "это неправда", image: "images/its_not_true.jpg", audio: "audio/its_not_true.mp3" },
        { word: "Get warm", translation: "согреться", image: "images/get_warm.jpg", audio: "audio/get_warm.mp3" },
        { word: "Move quickly", translation: "двигаться быстро", image: "images/move_quickly.jpg", audio: "audio/move_quickly.mp3" },
        { word: "Go camping", translation: "пойти в поход", image: "images/go_camping.jpg", audio: "audio/go_camping.mp3" },
        { word: "You need to be careful", translation: "тебе нужно быть осторожным", image: "images/need_to_be_careful.jpg", audio: "audio/need_to_be_careful.mp3" },
        { word: "The Spirit of a dead person", translation: "дух умершего человека", image: "images/spirit_of_dead.jpg", audio: "audio/spirit_of_dead.mp3" },
        { word: "The person's death", translation: "смерть человека", image: "images/persons_death.jpg", audio: "audio/persons_death.mp3" },
        { word: "Go hiking", translation: "ходить в поход / ходить в горы", image: "images/go_hiking.jpg", audio: "audio/go_hiking.mp3" },
        { word: "Pick apples", translation: "собирать яблоки", image: "images/pick_apples.jpg", audio: "audio/pick_apples.mp3" },
        { word: "Harvest", translation: "урожай; собирать урожай", image: "images/harvest.jpg", audio: "audio/harvest.mp3" },
        { word: "Don't mind", translation: "не против", image: "images/dont_mind.jpg", audio: "audio/dont_mind.mp3" },
        { word: "I allow him to play", translation: "я разрешаю ему играть", image: "images/allow_him_to_play.jpg", audio: "audio/allow_him_to_play.mp3" },
        { word: "Impatient", translation: "нетерпеливый", image: "images/impatient.jpg", audio: "audio/impatient.mp3" },
        { word: "Leave home on time", translation: "выходить из дома вовремя", image: "images/leave_home_on_time.jpg", audio: "audio/leave_home_on_time.mp3" },
        { word: "Broaden your horizons", translation: "расширять кругозор", image: "images/broaden_horizons.jpg", audio: "audio/broaden_horizons.mp3" },
        { word: "Experience new emotions", translation: "испытывать новые эмоции", image: "images/experience_emotions.jpg", audio: "audio/experience_emotions.mp3" }
    ],
    "September 2": [
        { word: "Do everything quickly", translation: "делать всё быстро", image: "images/do_everything_quickly.jpg", audio: "audio/do_everything_quickly.mp3" },
        { word: "Slow down", translation: "замедлиться", image: "images/slow_down.jpg", audio: "audio/slow_down.mp3" },
        { word: "Take a vacation", translation: "взять отпуск", image: "images/take_a_vacation.jpg", audio: "audio/take_a_vacation.mp3" },
        { word: "Promise", translation: "обещать", image: "images/promise.jpg", audio: "audio/promise.mp3" },
        { word: "Get takeout pizza", translation: "взять пиццу на вынос", image: "images/get_takeout_pizza.jpg", audio: "audio/get_takeout_pizza.mp3" },
        { word: "Also", translation: "тоже / так же", image: "images/also.jpg", audio: "audio/also.mp3" },
        { word: "Make them happy", translation: "радовать их", image: "images/make_them_happy.jpg", audio: "audio/make_them_happy.mp3" },
        { word: "Look good", translation: "выглядеть хорошо", image: "images/look_good.jpg", audio: "audio/look_good.mp3" },
        { word: "Swap clothes", translation: "обмениваться одеждой", image: "images/swap_clothes.jpg", audio: "audio/swap_clothes.mp3" },
        { word: "Prefer", translation: "предпочитать", image: "images/prefer.jpg", audio: "audio/prefer.mp3" },
        { word: "Walk in the park", translation: "гулять в парке", image: "images/walk_in_park.jpg", audio: "audio/walk_in_park.mp3" },
        { word: "I don't like doing that", translation: "я не люблю делать это", image: "images/dont_like_doing_that.jpg", audio: "audio/dont_like_doing_that.mp3" },
        { word: "Lead a healthy lifestyle", translation: "вести ЗОЖ", image: "images/lead_healthy_lifestyle.jpg", audio: "audio/lead_healthy_lifestyle.mp3" },
        { word: "Gain weight", translation: "набрать вес", image: "images/gain_weight.jpg", audio: "audio/gain_weight.mp3" },
        { word: "Lose weight", translation: "похудеть", image: "images/lose_weight.jpg", audio: "audio/lose_weight.mp3" },
        { word: "Go to sleep early", translation: "идти спать рано", image: "images/go_to_sleep_early.jpg", audio: "audio/go_to_sleep_early.mp3" },
        { word: "Everyone in my family", translation: "все в моей семье", image: "images/everyone_in_family.jpg", audio: "audio/everyone_in_family.mp3" },
        { word: "Have a shower", translation: "принимать душ", image: "images/have_a_shower.jpg", audio: "audio/have_a_shower.mp3" },
        { word: "It's hot in the summer", translation: "летом жарко", image: "images/its_hot_in_summer.jpg", audio: "audio/its_hot_in_summer.mp3" },
        { word: "To be clean", translation: "чтобы быть чистым", image: "images/to_be_clean.jpg", audio: "audio/to_be_clean.mp3" },
        { word: "To smell good", translation: "чтобы пахнуть хорошо", image: "images/to_smell_good.jpg", audio: "audio/to_smell_good.mp3" },
        { word: "Feel responsible", translation: "чувствовать себя ответственным", image: "images/feel_responsible.jpg", audio: "audio/feel_responsible.mp3" },
        { word: "Finish what I started", translation: "закончить начатое", image: "images/finish_what_i_started.jpg", audio: "audio/finish_what_i_started.mp3" },
        { word: "Have little time for sport", translation: "иметь мало времени для спорта", image: "images/little_time_for_sport.jpg", audio: "audio/little_time_for_sport.mp3" },
        { word: "Look younger", translation: "выглядеть моложе", image: "images/look_younger.jpg", audio: "audio/look_younger.mp3" },
        { word: "I reminded you of this", translation: "я напомнила вам об этом", image: "images/reminded_you.jpg", audio: "audio/reminded_you.mp3" },
        { word: "Anytime", translation: "в любое время", image: "images/anytime.jpg", audio: "audio/anytime.mp3" },
        { word: "Invite my friend to the restaurant", translation: "позвать мою подругу в ресторан", image: "images/invite_friend.jpg", audio: "audio/invite_friend.mp3" },
        { word: "Close people", translation: "близкие люди", image: "images/close_people.jpg", audio: "audio/close_people.mp3" },
        { word: "Good for health", translation: "полезно для здоровья", image: "images/good_for_health.jpg", audio: "audio/good_for_health.mp3" },
        { word: "Brush my teeth first", translation: "сначала почистить зубы", image: "images/brush_teeth.jpg", audio: "audio/brush_teeth.mp3" },
        { word: "Wash my face", translation: "умыть лицо", image: "images/wash_face.jpg", audio: "audio/wash_face.mp3" },
        { word: "Before", translation: "до", image: "images/before_2.jpg", audio: "audio/before_2.mp3" },
        { word: "After that", translation: "после этого", image: "images/after_that.jpg", audio: "audio/after_that.mp3" },
        { word: "Guests", translation: "гости", image: "images/guests.jpg", audio: "audio/guests.mp3" },
        { word: "I want to be", translation: "я хочу быть", image: "images/i_want_to_be.jpg", audio: "audio/i_want_to_be.mp3" },
        { word: "Skip the meal", translation: "пропустить прием пищи", image: "images/skip_meal.jpg", audio: "audio/skip_meal.mp3" },
        { word: "Feel frustrated", translation: "чувствовать фрустрацию", image: "images/feel_frustrated.jpg", audio: "audio/feel_frustrated.mp3" },
        { word: "Talk quickly", translation: "разговаривать быстро", image: "images/talk_quickly.jpg", audio: "audio/talk_quickly.mp3" },
        { word: "If", translation: "если", image: "images/if.jpg", audio: "audio/if.mp3" },
        { word: "Get enough sleep", translation: "высыпаться", image: "images/get_enough_sleep.jpg", audio: "audio/get_enough_sleep.mp3" },
        { word: "It's better to study online", translation: "лучше учиться онлайн", image: "images/study_online.jpg", audio: "audio/study_online.mp3" },
        { word: "Turn the volume down", translation: "уменьшить звук", image: "images/turn_volume_down.jpg", audio: "audio/turn_volume_down.mp3" },
        { word: "Get to work", translation: "доходить / добираться о работы", image: "images/get_to_work.jpg", audio: "audio/get_to_work.mp3" },
        { word: "Go to another city", translation: "поехать в другой город", image: "images/go_another_city.jpg", audio: "audio/go_another_city.mp3" },
        { word: "Far away (from)", translation: "далеко (от)", image: "images/far_away.jpg", audio: "audio/far_away.mp3" },
        { word: "Talk to her", translation: "пообщаться / поговорить с ней", image: "images/talk_to_her.jpg", audio: "audio/talk_to_her.mp3" },
        { word: "Draw a picture", translation: "нарисовать картинку", image: "images/draw_picture.jpg", audio: "audio/draw_picture.mp3" },
        { word: "Bored", translation: "скучно", image: "images/bored.jpg", audio: "audio/bored.mp3" },
        { word: "Drive a car", translation: "ездить на машине", image: "images/drive_a_car.jpg", audio: "audio/drive_a_car.mp3" },
        { word: "In the future", translation: "в будущем", image: "images/in_future.jpg", audio: "audio/in_future.mp3" },
        { word: "Find a job", translation: "найти работу", image: "images/find_a_job.jpg", audio: "audio/find_a_job.mp3" },
        { word: "Earn money", translation: "зарабатывать деньги", image: "images/earn_money.jpg", audio: "audio/earn_money.mp3" },
        { word: "Change", translation: "менять, изменить", image: "images/change.jpg", audio: "audio/change.mp3" },
        { word: "Forget somebody's name", translation: "забыть чье то имя", image: "images/forget_name.jpg", audio: "audio/forget_name.mp3" },
        { word: "Have a good memory", translation: "иметь хорошую память", image: "images/have_good_memory.jpg", audio: "audio/have_good_memory.mp3" },
        { word: "Give somebody flowers", translation: "дарить цветы", image: "images/give_flowers.jpg", audio: "audio/give_flowers.mp3" },
        { word: "Hear a noise", translation: "слышать шум", image: "images/hear_a_noise.jpg", audio: "audio/hear_a_noise.mp3" },
        { word: "Easily wake up", translation: "с легкостью просыпаться", image: "images/easily_wake_up.jpg", audio: "audio/easily_wake_up.mp3" },
        { word: "Help somebody", translation: "помогать", image: "images/help_somebody.jpg", audio: "audio/help_somebody.mp3" },
        { word: "Help other people", translation: "помогать другим людям", image: "images/help_other_people.jpg", audio: "audio/help_other_people.mp3" },
        { word: "Ask other people for help", translation: "просить помощи у других людей", image: "images/ask_help.jpg", audio: "audio/ask_help.mp3" },
        { word: "Solve problems by myself", translation: "решать проблемы самой", image: "images/solve_problems.jpg", audio: "audio/solve_problems.mp3" },
        { word: "Look for your keys", translation: "искать ключи", image: "images/look_for_keys.jpg", audio: "audio/look_for_keys.mp3" },
        { word: "Lose", translation: "терять", image: "images/lose.jpg", audio: "audio/lose.mp3" },
        { word: "Meet for a coffee", translation: "встретиться за кофе", image: "images/meet_for_coffee.jpg", audio: "audio/meet_for_coffee.mp3" },
        { word: "Coffee shop", translation: "кофейня", image: "images/coffee_shop.jpg", audio: "audio/coffee_shop.mp3" },
        { word: "Talk about everything", translation: "разговаривать обо всем", image: "images/talk_about_everything.jpg", audio: "audio/talk_about_everything.mp3" },
        { word: "Tell them about my problems", translation: "рассказывать им о своих проблемах", image: "images/tell_problems.jpg", audio: "audio/tell_problems.mp3" },
        { word: "They tell me about their problems", translation: "они рассказывают мне о своих проблемах", image: "images/they_tell_problems.jpg", audio: "audio/they_tell_problems.mp3" },
        { word: "Paint the walls", translation: "закрасить стены", image: "images/paint_walls.jpg", audio: "audio/paint_walls.mp3" },
        { word: "Make a renovation", translation: "делать ремонт", image: "images/make_renovation.jpg", audio: "audio/make_renovation.mp3" },
        { word: "Smell", translation: "запах, пахнуть", image: "images/smell.jpg", audio: "audio/smell.mp3" },
        { word: "It smells bad", translation: "пахнуть плохо", image: "images/smells_bad.jpg", audio: "audio/smells_bad.mp3" },
        { word: "Play chess", translation: "играть в шахматы", image: "images/play_chess.jpg", audio: "audio/play_chess.mp3" },
        { word: "Become smarter", translation: "становиться умнее", image: "images/become_smarter.jpg", audio: "audio/become_smarter.mp3" },
        { word: "See a movie", translation: "видеть фильм", image: "images/see_a_movie.jpg", audio: "audio/see_a_movie.mp3" },
        { word: "Sing a song", translation: "петь песню", image: "images/sing_a_song.jpg", audio: "audio/sing_a_song.mp3" },
        { word: "Swim in the ocean", translation: "плавать в океане", image: "images/swim_in_ocean.jpg", audio: "audio/swim_in_ocean.mp3" },
        { word: "I just don't sing", translation: "я просто не пою", image: "images/just_dont_sing.jpg", audio: "audio/just_dont_sing.mp3" },
        { word: "Go on vacation", translation: "поехать в отпуск", image: "images/go_on_vacation.jpg", audio: "audio/go_on_vacation.mp3" },
        { word: "Try to go to the sea on vacation", translation: "стараться ездить в море на отпуске", image: "images/try_go_to_sea.jpg", audio: "audio/try_go_to_sea.mp3" },
        { word: "Take photos of my family", translation: "фотографировать мою семью", image: "images/take_photos_family.jpg", audio: "audio/take_photos_family.mp3" },
        { word: "Talk about different things", translation: "разговаривать о разных вещах", image: "images/talk_different_things.jpg", audio: "audio/talk_different_things.mp3" },
        { word: "Try to do this in English", translation: "стараться делать это на английском", image: "images/try_do_in_english.jpg", audio: "audio/try_do_in_english.mp3" },
        { word: "Wait for a bus", translation: "ждать автобус", image: "images/wait_for_bus.jpg", audio: "audio/wait_for_bus.mp3" },
        { word: "It's cold outside", translation: "на улице холодно", image: "images/its_cold_outside.jpg", audio: "audio/its_cold_outside.mp3" },
        { word: "Especially", translation: "особенно", image: "images/especially.jpg", audio: "audio/especially.mp3" },
        { word: "Run slowly", translation: "бегать медленно", image: "images/run_slowly.jpg", audio: "audio/run_slowly.mp3" },
        { word: "Get home", translation: "добраться до дома", image: "images/get_home.jpg", audio: "audio/get_home.mp3" },
        { word: "On the bench", translation: "на скамейке", image: "images/on_the_bench.jpg", audio: "audio/on_the_bench.mp3" },
        { word: "Chair", translation: "стул", image: "images/chair.jpg", audio: "audio/chair.mp3" },
        { word: "Stand", translation: "стоять", image: "images/stand.jpg", audio: "audio/stand.mp3" },
        { word: "Grass", translation: "трава", image: "images/grass.jpg", audio: "audio/grass.mp3" },
        { word: "What about you?", translation: "что насчет вас?", image: "images/what_about_you.jpg", audio: "audio/what_about_you.mp3" },
        { word: "What's the weather like?", translation: "какая погода?", image: "images/whats_weather_like.jpg", audio: "audio/whats_weather_like.mp3" },
        { word: "How often does Ayazhan take a photo?", translation: "как часто Аяжан делает фото?", image: "images/ayazhan_take_photo.jpg", audio: "audio/ayazhan_take_photo.mp3" },
        { word: "Wet food", translation: "влажный корм", image: "images/wet_food.jpg", audio: "audio/wet_food.mp3" }
    ]
};
